services:
  mongo:
    image: mongo
    container_name: mongo-liveboard
    restart: always
    networks:
      - liveboard_network
    volumes:
      - mongo-data:/data/db
  backend:
    build:
      context: ./backend
    container_name: backend-liveboard
    restart: always
    networks:
      - liveboard_network
    environment:
      - CLUB_IDS=8422,200608
      - HTTP_PORT=5053
      - NODE_ENV=production
      - JWT_SECRET=AD#K#YQ7*zpTqnmX9mv3t9vSF8GW!MP@nUmptXXn2#xTDBzU#q9maDthdrh3
      - MONGO_URL=mongodb://mongo:27017/liveboardDB
    ports:
      - "5053:5053"
    volumes:
      - uploads-volume:/usr/src/app/assets/uploads # Montre le volume au dossier dans le conteneur

  frontend:
    build:
      context: ./frontend
    container_name: frontend-liveboard
    restart: always
    networks:
      - liveboard_network
    environment:
      - VITE_API_BASE_URL=https://api.liveboard.esmorannes.com
      - PRIMARY_LIGHT=#fff385
      - PRIMARY_DEFAULT=#ffde00
      - PRIMARY_DARK=#ccaf00
      - TEXT_COLOR=#000000
    ports:
      - "8083:8083"

volumes:
  uploads-volume:
  mongo-data:


networks:
  liveboard_network:
    external: true
